server:
  port: 8080

personal:
  database:
    ip: localhost
    port: 6060
    name: "financial_data_analysis"
    user:
      name: root
      password: taosdata
  knife4j:
    title: "基于SpringBoot的金融数据分析软件后台测试系统"
    version: "1.0"
    description: "开发人员专用"
    license: "Apache 2.0"
    name: "Jungle"
  front:
    token:
      head_key: "X-token"
      prefix: "userService.token:"
      expiration_time_in_days: 3



spring:
  application:
    name: FinancialDataAnalysisBoot

  datasource:
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    url: jdbc:TAOS-RS://${personal.database.ip}:${personal.database.port}/${personal.database.name}?useSSL=false&user=${personal.database.user.name}&password=${personal.database.user.password}&local=zh_CN.UTF-8&charset=UTF-8&timezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    test-while-idle: true
    validation-query: SELECT 1
  data:
    redis:
      database: 0
      host: 8.140.245.69
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
        shutdown-timeout: 100ms
      port: 6379
      password:


mybatis:
  mapper-locations: classpath:Mybatis/mapper/*.xml

knife4j:
  enable: true
  setting:
    language: zh_cn