server:
  port: 8080

personal:
  remoteService:
    ip: localhost
    port: 6060
  login:
    name: root
    password: taosdata
  database:
    name: "financial_data_analysis"
  knife4j:
    title: "基于SpringBoot的金融数据分析软件后台测试系统"
    version: "1.0"
    description: "开发人员专用"
    license: "Apache 2.0"
    name: "Jungle"


spring:
  application:
    name: FinancialDataAnalysisBoot

  datasource:
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    url: jdbc:TAOS-RS://${personal.remoteService.ip}:${personal.remoteService.port}/${personal.database.name}?useSSL=false&user=${personal.login.name}&password=${personal.login.password}&local=zh_CN.UTF-8&charset=UTF-8&timezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    test-while-idle: true
    validation-query: SELECT 1


mybatis:
  mapper-locations: classpath:Mybatis/mapper/*.xml

knife4j:
  enable: true
  setting:
    language: zh_cn
