server:
  port: 8080

personal:
  remoteService:
    ip: localhost
    port: 6060
  login:
    name: root
    password: taosdata
  database:
    name: "financial_data_analysis"

spring:
  application:
    name: FinancialDataAnalysisBoot

  datasource:
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    url: jdbc:TAOS-RS://${personal.remoteService.ip}:${personal.remoteService.port}/${personal.database.name}?useSSL=false&user=${personal.login.name}&password=${personal.login.password}&local=zh_CN.UTF-8&charset=UTF-8&timezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    test-while-idle: true
    validation-query: SELECT 1


mybatis:
  mapper-locations: classpath:Mybatis/mapper/*.xml